# KFold Cross Validation

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [2]:
df = pd.DataFrame(digits.data)
df.head()

0    1    2     3     4     5    6    7    8    9   ...   54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [3]:
df.shape

(1797, 64)

In [4]:
df['target'] = digits.target

In [5]:
df.head()

0    1    2     3     4     5    6    7    8    9  ...   55   56   57  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  0.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    58    59    60    61   62   63  target  
0  6.0  13.0  10.0   0.0  0.0  0.0       0  
1  0.0  11.0  16.0  10.0  0.0  0.0       1  
2  0.0   3.0  11.0  16.0  9.0  0.0       2  
3  7.0  13.0  13.0   9.0  0.0  0.0       3  
4  0.0   2.0  16.0   4.0  0.0  0.0       4  

[5 rows x 65 columns]

In [6]:
X = df.drop('target', axis='columns')
y = df.target

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

#### Logistic Regression

In [12]:
lr = LogisticRegression(solver='liblinear', multi_class='ovr')
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9722222222222222

#### SVM

In [13]:
svm = SVC(gamma='auto')
svm.fit(X_train,y_train)
svm.score(X_test, y_test)

0.37592592592592594

#### Rondom Forest

In [21]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9777777777777777

## KFold Cross Validation

Basic Example<br> 
Only for understanding, how KFold Cross validation work

In [22]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [23]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


#### Use KFold on Digits Example

In real world model we do not write this type of too much code this below code only for understanding

In [24]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [71]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic=[]
scores_svm=[]
scores_rf=[]

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear', multi_class='ovr'), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=60), X_train, X_test, y_train, y_test))

In [72]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [73]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [74]:
scores_rf

[0.9298831385642737, 0.9565943238731218, 0.9332220367278798]

## cross_val_score function

In real world model we use this method, we don't write long code to use KFold

In [75]:
from sklearn.model_selection import cross_val_score

#### Logistic regression model performance using cross_val_score

In [77]:
cross_val_score(LogisticRegression(solver='liblinear', multi_class='ovr'), X, y, cv=3)

array([0.89482471, 0.95325543, 0.90984975])

#### svm model performance using cross_val_score

In [78]:
cross_val_score(SVC(gamma='auto'), X, y, cv=3)

array([0.38063439, 0.41068447, 0.51252087])

#### random forest performance using cross_val_score

In [88]:
cross_val_score(RandomForestClassifier(n_estimators=50), X, y, cv=3)

array([0.93656093, 0.95659432, 0.92988314])

cross_val_score uses stratifield kfold by default

## Parameter tunning using k fold cross validation

In [89]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5), X, y, cv=10)
np.average(scores1)

0.8787026691495965

In [90]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=10), X, y, cv=10)
np.average(scores2)

0.9165021725636253

In [91]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=20), X, y, cv=10)
np.average(scores3)

0.9320856610800744

In [92]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=30), X, y, cv=10)
np.average(scores4)

0.9415580384854128

In [93]:
scores5 = cross_val_score(RandomForestClassifier(n_estimators=40), X, y, cv=10)
np.average(scores5)

0.9432495344506517

In [94]:
scores6 = cross_val_score(RandomForestClassifier(n_estimators=50), X, y, cv=10)
np.average(scores6)

0.9488081936685289

Here we used cross_val_score to fine tune our random forest classifier and figured that having around 50 trees in random forest gives best result.